
Это файл для организации работы
<<<<<<< HEAD
* Начало работы
  SCHEDULED: <2015-10-17 Сб>
Здесь буду записывать ход работ и планирование работ
* Векторы
** 1. Использование базы данных
алтернативы
mysql
postgresql
mongodb
** 2. Использование языков программирования.
альтернативы
forth
factor
php
c++
erlang
haskell
Попутно
xml, xslt
** 3. Общая структура
Клиент-серверная структура
база данных располагается где-то на хостинге, возможно на другом хостинге располагается приложение сервер.
клиентские приложения: веб и персональные клиенты под фбсд, лин, винду, андроид
Клиентское приложение должно уметь отрисовывать графические данные (линии, окружности, дуги, точки)

*** Структура приложения
**** Общие требования
1. Модульность. 
2. Многоязыковость
3. Уровни приложения.
Слой А. Интерфейс пользователя
Слой Б. Командная строка.
Слой В. Макросы автоматизации
Слой Г. Работа с хранилищами данных. Этот слой должен позволять абстрагироваться от конкретных хранилищь данных и позволять работать с данными не зависимо от того, где и в каком хранилище находятся данные. 
Слой Г.1 Это подслой для работы с различными драйверами данных, который приводит данный из разных источников к унифицированному виду для дальнейшей их обработки.
Слой Г.1.1 Это слой непосредственно самих драйверов.

**** Серверная часть
**** Клиентская часть

** 3. Хостинг.
Для начала необходимо выбрать надежный хостинг желательно бесплатный для разработки и тестирования. Кроме этого необходимо на локальном сервере поддерживать хостинг на случай если нет интернета. Также нужна система позволяющая быстро переезжать с одного хостинга на другой.
*** Домашний хостинг
Развернуть в дополнение к установленному OpenServer языки программирования
- форт sp-forth
- фактор Factor Slava Pestov
- эрланг erlang
- хаскель haskell
*** Забрать у Олега свои железки
*** Развернуть FBSD и виртуальные машины
- лин
- фбсд

*** 3.1 Поиск и выбор хостинга.
*** Поднять хостинг на sourceforge.net для проекта и на github.com
**** Организовать хранение и разработку проекта на git
Развернуть локальное хранилище
Научиться работать с git
Залить хранилище на github.com and sourceforge.net
Там же завести блог и стреничку с описанием проекта.

*** Уроки
**** forth
**** factor
**** erlang
**** haskell
**** lisp (emacs lisp)
** Прочие задачи
*** Написать программу, которая создает проект_компонент joomla
**** Работа программы
Запросить имя компонента
Запросить место для проекта
Создать структуру проекта компонента в соответствии с MVC
Создать файл описания проекта com_name.xml
Создать все другие файлы в соответствии с MVC
***** Создать xml файл для хранения данных о проекте
****** Вариант 1
этап 1
Вызвать set-component-buffer
Это запросит имя компонента
Далее используя это имя создать буффер с именем com_имя-компонента.xml
Далее вставить в буфер заголовок xml
этап 2
Далее сохранить буфер 
Для этого запросить путь для размешения проекта компонента и сохранить туда буффер
=======

Описание проектов
Проекты на форте.
* проект расчетов типа управление кошельком. Кому или кто и сколько должен. По указанному клиенту либо сводка
* проектСтатистика по посту с записью состояний и правил с переносом проекта на веб сайт. В рамках этого проекта создание приложения для андроид и айпад с возможностью сбора пожертвований. Что весьма приятно.

>>>>>>> origin/master
